### ISSUE TITLE
Add UML Diagrams to Wiki

### ISSUE THREAD

**Issue by ksteinfeldt** [OSU-CS361-W17/group21_project3#11]
Scan and add this diagram to your group's Wiki pages (names should be added to indicate the author of each diagram).

**Comment by jonhadi** [comment]
Probably just do this on our meeting March 2, Thursday. Have your diagrams done by then

**Comment by ksteinfeldt** [comment]
Expected has been added.

**Comment by johnbren85** [comment]
Added Actual
